[project]
name = "windycity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=7.1.1",
    "jupyter>=1.1.1",
    "polymathic-aion>=0.0.2",
]
